using System.Globalization;
using System.IO;
using System.Text;
using System.Windows.Media.Media3D;

namespace DCMViewer.Services;

internal static class MeshExportService
{
    internal sealed record MeshSnapshot(Point3D[] Positions, int[] TriangleIndices);
    internal sealed record MeshExportItem(string DisplayName, MeshSnapshot Mesh);

    public static MeshSnapshot CreateSnapshot(MeshGeometry3D mesh)
    {
        ArgumentNullException.ThrowIfNull(mesh);

        return new MeshSnapshot(
            mesh.Positions.ToArray(),
            mesh.TriangleIndices.ToArray());
    }

    public static void Export(string filePath, IReadOnlyList<MeshSnapshot> meshes)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(filePath);
        ArgumentNullException.ThrowIfNull(meshes);

        if (meshes.Count == 0)
        {
            throw new InvalidOperationException("No mesh data is available to export.");
        }

        var extension = Path.GetExtension(filePath);
        if (string.Equals(extension, ".stl", StringComparison.OrdinalIgnoreCase))
        {
            WriteBinaryStl(filePath, meshes);
            return;
        }

        if (string.Equals(extension, ".ply", StringComparison.OrdinalIgnoreCase))
        {
            WriteAsciiPly(filePath, meshes);
            return;
        }

        throw new NotSupportedException($"Unsupported export format '{extension}'.");
    }

    public static void ExportSeparateStl(string baseFilePath, IReadOnlyList<MeshExportItem> meshes)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(baseFilePath);
        ArgumentNullException.ThrowIfNull(meshes);

        if (meshes.Count == 0)
        {
            throw new InvalidOperationException("No mesh data is available to export.");
        }

        var directory = Path.GetDirectoryName(baseFilePath);
        if (string.IsNullOrWhiteSpace(directory))
        {
            directory = Environment.CurrentDirectory;
        }

        var baseName = Path.GetFileNameWithoutExtension(baseFilePath);
        if (string.IsNullOrWhiteSpace(baseName))
        {
            baseName = "visible-meshes";
        }

        var usedNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var item in meshes)
        {
            var safeName = MakeSafeFileName(Path.GetFileNameWithoutExtension(item.DisplayName));
            if (string.IsNullOrWhiteSpace(safeName))
            {
                safeName = "mesh";
            }

            var fileNameBase = $"{baseName}_{safeName}";
            var uniqueFileNameBase = fileNameBase;
            var suffix = 2;
            while (!usedNames.Add(uniqueFileNameBase))
            {
                uniqueFileNameBase = $"{fileNameBase}_{suffix++}";
            }

            var outputPath = Path.Combine(directory, uniqueFileNameBase + ".stl");
            WriteBinaryStl(outputPath, new[] { item.Mesh });
        }
    }

    private static void WriteBinaryStl(string filePath, IReadOnlyList<MeshSnapshot> meshes)
    {
        var triangleCount = meshes.Sum(GetTriangleCount);
        if (triangleCount <= 0)
        {
            throw new InvalidOperationException("The selected meshes do not contain any triangles.");
        }

        using var stream = File.Create(filePath);
        using var writer = new BinaryWriter(stream, Encoding.ASCII, leaveOpen: false);

        var header = new byte[80];
        Encoding.ASCII.GetBytes("DCMViewer STL export", 0, "DCMViewer STL export".Length, header, 0);
        writer.Write(header);
        writer.Write((uint)triangleCount);

        foreach (var mesh in meshes)
        {
            foreach (var triangle in EnumerateTriangles(mesh))
            {
                var normal = ComputeNormal(triangle.P0, triangle.P1, triangle.P2);
                WriteVector(writer, normal);
                WritePoint(writer, triangle.P0);
                WritePoint(writer, triangle.P1);
                WritePoint(writer, triangle.P2);
                writer.Write((ushort)0);
            }
        }
    }

    private static void WriteAsciiPly(string filePath, IReadOnlyList<MeshSnapshot> meshes)
    {
        var totalVertices = meshes.Sum(mesh => mesh.Positions.Length);
        var totalFaces = meshes.Sum(GetTriangleCount);
        if (totalFaces <= 0)
        {
            throw new InvalidOperationException("The selected meshes do not contain any triangles.");
        }

        using var writer = new StreamWriter(filePath, false, new UTF8Encoding(false));
        writer.WriteLine("ply");
        writer.WriteLine("format ascii 1.0");
        writer.WriteLine("comment Generated by DCMViewer");
        writer.WriteLine($"element vertex {totalVertices}");
        writer.WriteLine("property float x");
        writer.WriteLine("property float y");
        writer.WriteLine("property float z");
        writer.WriteLine($"element face {totalFaces}");
        writer.WriteLine("property list uchar int vertex_indices");
        writer.WriteLine("end_header");

        foreach (var mesh in meshes)
        {
            foreach (var position in mesh.Positions)
            {
                writer.WriteLine($"{Format(position.X)} {Format(position.Y)} {Format(position.Z)}");
            }
        }

        var vertexOffset = 0;
        foreach (var mesh in meshes)
        {
            foreach (var (i0, i1, i2) in EnumerateTriangleIndices(mesh))
            {
                writer.WriteLine($"3 {vertexOffset + i0} {vertexOffset + i1} {vertexOffset + i2}");
            }

            vertexOffset += mesh.Positions.Length;
        }
    }

    private static int GetTriangleCount(MeshSnapshot mesh)
    {
        if (mesh.TriangleIndices.Length >= 3)
        {
            return mesh.TriangleIndices.Length / 3;
        }

        return mesh.Positions.Length / 3;
    }

    private static IEnumerable<(Point3D P0, Point3D P1, Point3D P2)> EnumerateTriangles(MeshSnapshot mesh)
    {
        foreach (var (i0, i1, i2) in EnumerateTriangleIndices(mesh))
        {
            if (i0 < 0 || i1 < 0 || i2 < 0 ||
                i0 >= mesh.Positions.Length || i1 >= mesh.Positions.Length || i2 >= mesh.Positions.Length)
            {
                continue;
            }

            yield return (mesh.Positions[i0], mesh.Positions[i1], mesh.Positions[i2]);
        }
    }

    private static IEnumerable<(int I0, int I1, int I2)> EnumerateTriangleIndices(MeshSnapshot mesh)
    {
        if (mesh.TriangleIndices.Length >= 3)
        {
            for (var index = 0; index + 2 < mesh.TriangleIndices.Length; index += 3)
            {
                yield return (mesh.TriangleIndices[index], mesh.TriangleIndices[index + 1], mesh.TriangleIndices[index + 2]);
            }

            yield break;
        }

        for (var index = 0; index + 2 < mesh.Positions.Length; index += 3)
        {
            yield return (index, index + 1, index + 2);
        }
    }

    private static Vector3D ComputeNormal(Point3D p0, Point3D p1, Point3D p2)
    {
        var edge1 = p1 - p0;
        var edge2 = p2 - p0;
        var normal = Vector3D.CrossProduct(edge1, edge2);
        if (normal.LengthSquared > 1e-12)
        {
            normal.Normalize();
            return normal;
        }

        return new Vector3D(0, 0, 0);
    }

    private static void WriteVector(BinaryWriter writer, Vector3D vector)
    {
        writer.Write((float)vector.X);
        writer.Write((float)vector.Y);
        writer.Write((float)vector.Z);
    }

    private static void WritePoint(BinaryWriter writer, Point3D point)
    {
        writer.Write((float)point.X);
        writer.Write((float)point.Y);
        writer.Write((float)point.Z);
    }

    private static string Format(double value)
        => value.ToString("R", CultureInfo.InvariantCulture);

    private static string MakeSafeFileName(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return string.Empty;
        }

        var invalidChars = Path.GetInvalidFileNameChars();
        var builder = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            builder.Append(invalidChars.Contains(ch) ? '_' : ch);
        }

        return builder.ToString().Trim();
    }
}
